### ISSUE TITLE
Update benchmark

### ISSUE THREAD

**Issue by OneOfOne** [cespare/xxhash#9]
First, I'd like to say this is absolutely brilliant.

I updated my xxhash a little bit, I was wondering if you can try it again (or maybe show me how you did the benchmarks and I'll put up a PR with updated numbers.

**Comment by cespare** [comment]
I reran all the benchmarks in e4e2bd419cbedb5b2ec48e4a88e4c993ddb74555. I also included the commands I used.

I ran these on a different computer than last time (I think the last time was on a laptop; the new ones are from a c5.2xlarge instance in EC2).

At this point it's almost silly to include benchmark numbers since there's no practical speed difference between implementations. (And the assembly is nearly pointless.)
